---
title: Dorchester Euro Café
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: ''
email: dorchestereurocafe@gmail.com
url: https://dorchestereurocafe.github.io
description: Plotting the route to rejoining the European Union through coffee, cake
  and conversation
keywords: brexit, dorset, dorchester, EU, european, rejoin
skills: Web Developer - Graphic Artist - User Experience Designer
meta_author: Euro Cafe Dorchester
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 18bc9c
  primary-rgb: 179, 204, 255
  secondary: '003399'
  secondary-dark: FFCC00
footer:
  copyright: Dorchester Euro Café
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: http://twitter.com/EuroCafeDorch
- title: facebook
  url: 
- title: stack-overflow
  url: http://stackoverflow.com/questions/tagged/jekyll
- title: bitbucket
  url: http://bitbucket.org/jekyll
- title: github
  url: http://github.com/jekyll
address:
- line: 3481 Melrose Place
- line: Beverly Hills, CA 90210
credits: Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start
  Bootstrap</a>.
markdown: kramdown
permalink: pretty
